---
development:
  dialect: postgres
  database: widget-spinners
  user: postgres
  password: Matwyenko1_
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/migrations_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/migrations_production?sslmode=disable"}}
